# Generated by Django 4.1.2 on 2022-11-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=15)),
                ('time_period', models.CharField(max_length=15)),
                ('responsibilites', models.CharField(max_length=200)),
                ('project_title', models.CharField(max_length=20)),
                ('project_description', models.CharField(max_length=50)),
                ('achievement_title', models.CharField(max_length=15)),
                ('achievement_description', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField()),
                ('header_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.header_models')),
            ],
        ),
    ]
