# Generated by Django 4.1.2 on 2022-11-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Body',
            new_name='Body_models',
        ),
    ]
