# Generated by Django 4.1.2 on 2023-02-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0002_rename_body_body_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=15)),
                ('time_period', models.CharField(max_length=15)),
                ('responsibilites', models.CharField(max_length=200)),
                ('project_title', models.CharField(max_length=20)),
                ('project_description', models.CharField(max_length=50)),
                ('achievement_title', models.CharField(max_length=15)),
                ('achievement_description', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Body_models',
        ),
        migrations.DeleteModel(
            name='Header_models',
        ),
        migrations.AddField(
            model_name='body',
            name='header_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.header'),
        ),
    ]
